version = 0.1
[default.deploy.parameters]
stack_name = "spending-tracker-api"
resolve_s3 = true
s3_prefix = "spending-tracker-api"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
