AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 60

Resources:
  ProductApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.spendingTracker.SpendingTracker.StreamLambdaHandler::handleRequest
      Runtime: java17
      VpcConfig:
        SecurityGroupIds:
          - sg-0e0204b1c59588b74
        SubnetIds:
          - subnet-0ed8376a38c3cba4d
          - subnet-0fa02b178f699e57d
          - subnet-05b184902e50cddc5
          - subnet-0eea081e8b0a1e57a
          - subnet-06da7c36ae9d368d1
          - subnet-0e73c22bcf5cf57eb
      Architectures:
        - x86_64
      MemorySize: 800
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
          MYSQL_HOST: rds-spending-tracker-db.cdmiewgukza1.us-east-1.rds.amazonaws.com
          SPRING_DATASOURCE_URL: jdbc:mysql://rds-spending-tracker-db.cdmiewgukza1.us-east-1.rds.amazonaws.com:3306/spending_tracker
          SPRING_DATASOURCE_USERNAME: admin
          SPRING_DATASOURCE_PASSWORD: RDSPassword
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: arn:aws:secretsmanager:us-east-1:025066278641:secret:product-db-cred-7criSX
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
